apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: how-are-you-
spec:
  entrypoint: how-are-you
  
  templates:
  - name: how-are-you
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["how are you"] 
  