apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: diamond-
spec:
  entrypoint: diamond
  
  templates:
  - name: hello-world
    inputs:
      parameters:
      - name: script
    container:
      image: docker/whalesay
      command: [cowsay]
      args: ["{{inputs.parameters.script}}"]

  - name: diamond
    dag:
      tasks: 
        - name: A 
          template: hello-world
          arguments:
              parameters:
                - name: script
                  value: "how are you"
        - name: B
          template: hello-world
          arguments:
              parameters:
                - name: script
                  value: "good to see you!"
          dependencies: [A]
        - name: C
          template: hello-world
          arguments:
              parameters:
                - name: script
                  value: "take care"
          dependencies: [A]
        - name: D
          template: hello-world
          arguments:
              parameters:
                - name: script
                  value: "good bye!"
          dependencies: [B, C]