apiVersion: argoproj.io/v1alpha1
kind: CronWorkflow
metadata:
  name: hello-world
spec:
  schedule: "*/1 * * * *"
  timezone: "Asia/Kolkata" 
  concurrencyPolicy: "Replace"   
  successfulJobsHistoryLimit: 4   
  failedJobsHistoryLimit: 4       
  workflowSpec:
    entrypoint: whalesay
    templates:
      - name: whalesay
        container:
          image: docker/whalesay:latest
          command: [cowsay]
          args: ["🕓 hello world"]